version: "3"

services:
 website:
  image: georgejolema/subastang2webapp:latest
  restart: always
  ports:
   - "8080:8080"

 db:
  image: 'bitnami/mongodb:latest'
  restart: always
  ports:
   - "27017:27017"
  volumes:
   - /usr/local/mongodb:/data/db

 webapi:
  depends_on:
   - db
  image: georgejolema/subastang2api:latest
  ports:
   - "3000:3000"
